spring.application.name=SpringSecurity

# Database Configuration (Injected from .env)
spring.datasource.url=jdbc:postgresql://localhost:5432/etec_springsecurity
spring.datasource.username=postgres
spring.datasource.password=1


#cloudinary_java
# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


jwt.secret=my-super-secret-key-for-jwt-authentication-project-Sak-2026
jwt.expiration=3600000

server.port=9090
